// Combine Media Queries
// https://github.com/frontendfriends/grunt-combine-mq
module.exports = {
  dist: {
    default_options: {
      expand: true,
      src: 'styles.css', // generated by cssmin
      dest: 'styles.css',
    },
  }
};
